version: '3'
services:
  laspress:
    build: ./testdocker
    ports:
      - "5000:5000"
    depends_on: 
      - "lasbase"
    links:
      - "lasbase"
  lasbase:
    image: "mysql"
    ports:
      - "9009:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "database"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10